### ISSUE TITLE
Android BUILD FAILED version 8.3.6

### ISSUE THREAD

**Issue by chiaramistro** [Pushwoosh/pushwoosh-phonegap-plugin#377] opened 2022-09-08 08:59 UTC
Hello,
after the update of "pushwoosh-cordova-plugin" version 8.3.6 I get an error when I try to build my android app. I had to downgrade to 8.3.4 again to have a successful build. Is this problem going to be solved soon?

> /platforms/android/app/src/main/java/com/pushwoosh/plugin/pushnotifications/PushNotifications.java:182: error: cannot find symbol
> 					if (result.isSuccess() && result.getData != null) {
> 					                                ^
>   symbol:   variable getData
>   location: variable result of type Result<RegisterForPushNotificationsResultData,RegisterForPushNotificationsException>
>   
> BUILD FAILED in 15s

Ionic:

   Ionic CLI          : 5.4.16 (/.nvm/versions/node/v14.19.1/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 9.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.0, (and 33 other plugins)

System:

   ios-sim : 8.0.2
   NodeJS  : v14.19.1 (/.nvm/versions/node/v14.19.1/bin/node)
   npm     : 6.14.16
   OS      : macOS Monterey
   Xcode   : Xcode 13.4.1 Build version 13F100

**Comment by wfhm** [comment] 2022-09-14 08:52
@wfhm duplicate of #374. Will be fixed shortly.

**Closed by wfhm** 2022-09-14 08:52 UTC
Labels: 72820
