### ISSUE TITLE
[Bug]: iOS push-receive event does not trigger after force-closed app

### ISSUE THREAD

**Issue by zarko-tg** [Pushwoosh/pushwoosh-phonegap-plugin#407] opened 2024-09-18 10:56 UTC
### Documentation

- [X] I've checked the guide, but it doesn't help me to resolve the issue.

### Description

This is about a problem as observed with plugin ver. 8.3.30 on iOS.
It seems that the 'push-receive' event stops working if the app has been force-closed (swiped out from the screen), which might also be the case when the system decides to do the same.

### Bug severity

High

### Steps to Reproduce

1. Open the app
2. Receive a push -> observe that the 'push-receive' is triggered as expected.
3. Force-close the app and then start it again.
4. From this point on 'push-receive' does not seem to trigger at all.

### Your Pushwoosh Cordova plugin version

Other — specify it in the description

### cordova package version

Capacitor 6

### Affected platforms

- [ ] Android
- [X] iOS

### Affected OS versions and/or devices

iOS 18, iPhone

**Comment by akidisdev** [comment] 2024-09-21 10:06
Hi @zarko-tg,

I’m pleased to inform you that we’ve resolved the bug you reported. The issue has been fixed in version 8.3.32 of the pushwoosh-cordova-plugin.

Let us know if the problem is resolved!

**Comment by zarko-tg** [comment] 2024-09-23 09:40
Hi, thanks for that.
Things seem better now but it looks to me that there's still something that isn't working.
So far with the latest plugin version (8.3.32), I have found one related case that seems to fail.
1. Make sure the app is not in memory / not backgrounded (force close it by swipe up).
2. Send/receive a notification.
3. When the OS shows the notification tap on it (the app will naturally open).
4. Now 'push-receive' no longer triggers in foreground (until one force closes the app by swiping it up).

Hopefully you can reproduce this faulty behavior.

**Comment by akidisdev** [comment] 2024-09-30 10:18
Hi Zarko-tg,

We’ve fixed this bug in version 8.3.33. Please update to the latest version, and the issue should be resolved.

Let us know if anything else comes up!

**Comment by zarko-tg** [comment] 2024-10-01 07:47
Hi,

I made some quick tests and it seems that this issue is resolved now. At the same time I noticed that it might be a step back when it comes to the conflict with another plugin such as @capacitor/local-notifications (https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/issues/392).

I'll be doing more testing in a day or so.

**Closed** 2024-10-08 11:28 UTC
Labels: bug
