### ISSUE TITLE
Badge missing on iOS 9, plugin version 3.6.16

### ISSUE THREAD

**Issue by darina23** [Pushwoosh/pushwoosh-phonegap-plugin#154] opened 2016-01-22 18:01 UTC
For fixing twice alerts issue #125, I upgraded plugin to version 3.6.16. Alerts work nice but the problem is with badge on iOS9. It is absent and pushNotification.setApplicationIconBadgeNumber(number) is not working without any errors. Everything works good with the same build on iOS8.

**Comment by vefimov** [comment] 2016-01-23 07:37
It seems like badge number was broken after fix on android (starting from version 3.6.11). On 3.6.10 everything works well.

**Comment by vefimov** [comment] 2016-01-28 10:31
Any update on this ?

**Comment by DimanAM** [comment] 2016-01-29 13:08
I cannot reproduce this problem. There is nothing related to iOS in 3.6.11 changeset and there is nothing specific in iOS9 regarding badge number.
Did you accidentially disable "Badge App Icon" in notification settings?

**Comment by shaders** [comment] 2016-01-29 13:10
@vefimov Do you mean you cannot set the badge from Javascript API or from push notification?

**Comment by vefimov** [comment] 2016-01-29 17:06
@shaders I can't set badge number from Javascript API as well as from server (by server I mean POST request on /createMessage)

**Comment by shaders** [comment] 2016-02-11 05:33
I can't reproduce this, can you share a simple sample? Are you sure the app is closed when you receive push with badge?

**Comment by shaders** [comment] 2016-03-17 00:09
closing dead thread

**Closed by shaders** 2016-03-17 00:09 UTC
