### ISSUE TITLE
iOS inApp push-notification event not firing

### ISSUE THREAD

**Issue by rsirunesys** [Pushwoosh/pushwoosh-phonegap-plugin#261] opened 2017-09-10 16:21 UTC
Foreground (in app) notifications not coming through
Issue present in 7.0.6
Issue not present in 7.0.5 and prior
PhoneGap Build cli-6.5.0

**Comment by wfhm** [comment] 2017-09-11 05:35
Hi,

Could you please specify which platform is in question?

**Comment by wfhm** [comment] 2017-09-11 05:36
Hi,

Checking this.

**Comment by wfhm** [comment] 2017-09-13 07:53
@rsirunesys 

Could you please describe the issue in a bit more details? What do you mean by In App notifications? Did you mean [In-app messages](http://docs.pushwoosh.com/docs/in-app-messages) feature or were you talking about regular push notifications received in foreground state?

**Comment by mhueserNDR** [comment] 2017-09-13 10:06
Im having the same problem since the last update for a regular push notification in foreground state

**Comment by rsirunesys** [comment] 2017-09-13 14:13
Regular push notifications received in foreground state.  This code works under 7.0.5 but does not work under 7.0.6.

document.addEventListener('push-notification', function(event) {
		//get the notification payload
		var notification = event.notification;
		alert('we got a message');
	});

**Comment by rsirunesys** [comment] 2017-09-13 14:14
Sorry... hit the wrong button and closed the issue.  Re-opened now.

**Comment by wfhm** [comment] 2017-09-14 08:00
@rsirunesys @mhueserNDR 

With the latest release, we have reworked the logics of showing notification alerts/banners and handling pushes in foreground to make it more simple and clear. Now this behavior only depends on Pushwoosh_ALERT_TYPE flag in your info.plist. By default, this value is set to NONE (push is handled automatically when received, banner/ alert is not shown).

Therefore, if you want to show an alert or a banner when receiving push in foreground state, you should set an ALERT or a BANNER value for this flag. Use the following command:

```
cordova plugin add pushwoosh-cordova-plugin --variable IOS_FOREGROUND_ALERT_TYPE="ALERT"
```

Please refer to the docs below for additional details:
http://docs.pushwoosh.com/docs/customizing-cordova-plugin#push-notifications-in-foreground

**Comment by wfhm** [comment] 2017-09-14 12:04
@rsirunesys @mhueserNDR 

Turned out it is indeed an unexpected behavior, the issue is reopened. A fix will be rolled out shorty.

**Comment by kirajhpang** [comment] 2017-09-19 16:27
Hi I was using this as config.xml
```
 <plugin name="pushwoosh-cordova-plugin" spec="^7.0.5">
        <variable name="IOS_FOREGROUND_ALERT_TYPE" value="BANNER" />
        <variable name="ANDROID_FOREGROUND_PUSH" value="true" />
        <variable name="LOG_LEVEL" value="DEBUG" />
    </plugin>
```

But iOS doesn't show as BANNER when notification receive in foreground, it need use following listener to show as BANNER

```
document.addEventListener('push-notification', function (event: any) {
      //get the notification payload
      var notification = event.notification;

      //display alert to the user for example
      alert(notification.aps.alert);

      //clear the app badge
      pushNotification.setApplicationIconBadgeNumber(0);
    });
```

if this case, it is no able to handle action on click the notification. Anyway to solve this issue in iOS?

**Comment by jQrgen** [comment] 2017-09-19 17:09
I have kind of the same issue with version 7.0.6

the `push-notification` event fires when app is in background or closed, but not when in foreground.

**Comment by rsirunesys** [comment] 2017-09-19 17:28
Use 7.0.5 - it's ok for foreground.

**Comment by jQrgen** [comment] 2017-09-19 17:40
Thanks, @rsirunesys it works. 

Also for you guys at pushwoosh I would be very thankful if you implemented a QA checklist for basic functionality before publishing new versions of this plugin.

**Comment by kirajhpang** [comment] 2017-09-27 01:38
@rsirunesys @jQrgen 
Does 7.0.5 still need use following code for display banner? I currently stuck in onClick Notification handler, I believe this listen on this event, but If I change code behaviour on here, it doesn't show Banner at all. 
```
document.addEventListener('push-notification', function (event: any) {
      //get the notification payload
      var notification = event.notification;

      //display alert to the user for example
      alert(notification.aps.alert);

      //clear the app badge
      pushNotification.setApplicationIconBadgeNumber(0);
    });
```

**Comment by wfhm** [comment] 2017-09-27 07:27
Fixed in 7.0.7

**Closed by wfhm** 2017-09-27 07:27 UTC

**Comment by kirajhpang** [comment] 2017-09-27 07:33
@wfhm will get it a try..!! thanks the update

**Comment by rsirunesys** [comment] 2017-09-27 19:20
7.0.7 posted 5 days ago... no update here... would have been nice to know it was released.

7.0.7 under PhoneGap Build 6.5.0 fails to build.  7.0.5 has a successful build.

Can this issue be re-opened... or is it a different issue?

[PGB_650_PW707.txt](https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/files/1338459/PGB_650_PW707.txt)

**Comment by wfhm** [comment] 2017-09-28 02:15
@rsirunesys I strongly apologize for not updating you timely!

As for iOS build failing with Phonegap Build with the latest version of Pushwoosh plugin, it is a known issue. 7.0.7 release includes support of iOS 11, which requires XCode 9. Adobe have not yet updated cordova-ios for PGB, thus it is failing. It works fine when building locally with the latest XCode though.

You can use earlier versions of pushwoosh-cordova-plugin (not higher than 7.0.4) for iOS with Phonegap Build until Adobe includes support of the latest XCode.

**Comment by rsirunesys** [comment] 2017-09-28 02:31
Thanks @wfhm ... appreciated.

Why not higher than 7.0.4?  Just curious.  7.0.5 builds ok.

**Comment by wfhm** [comment] 2017-09-28 02:57
@rsirunesys 

7.0.4 does not differ from 7.0.5 from iOS perspective, however if you maintain both platforms, changes made for Android in 7.0.5 were rolled back in 7.0.6, so 7.0.4 is preferable in general.

**Comment by rsirunesys** [comment] 2017-09-28 02:59
Understood... perfect... thank you... 7.0.4 it is.

**Comment by kirajhpang** [comment] 2017-09-28 09:48
@wfhm thanks for the update, 7.0.7 is working very well.
